[system]
version = 1

[logging]
name = "wastepro"
path = "_log/wastepro.log"
level = "VERBOSE"  # VERBOSE, DEBUG, INFO, WARNING, ERROR

[broker]
broker_name = "mqtt01"

[broker.mqtt01]
broker_type = "mqtt"
host = "localhost"
port = 1883
username = ""
password = ""
keepalive = 60

[service]

[service.file]
home_directory = "_upload"

[service.llm]
openai_api_key = ""

[service.kg]
# The docker host and data path for docker container
hostname = "localhost"
datapath = "path/to/docker/volume"
