[system]
version = 1

[broker]
broker_type = "mqtt"
# broker_type = "amqp"

[broker.mqtt]
host = "localhost"
port = 1884
username = "eric"
password = "eric123"
keepalive = 60

[broker.amqp]
host = "amqp_host"
port = 5672
username = "amqp_user"
password = "amqp_pass"
heartbeat = 30
